// src/App.vue
<script setup>
import {ref} from "vue";

defineProps({
    hello: { type: String, default: '' },
    serverTime: { type: String, default: '' }
});

const count = ref(0);
function add() {
    count.value++;
}
</script>

<template>
    <div class="island">
        <h2>Hello, {{ hello }}!</h2>
        <p>Rendered server-side at: <code>{{ serverTime }}</code></p>
        <p>Hydrated client-side by Vue.</p>
        <button @click="add()">{{count}}</button>
    </div>
</template>

<style scoped>
.island {
    border: 2px solid #42b883;
    border-radius: 8px;
    padding: 1rem;
    background: #f5fbf8;
}
</style>

// demos/react/App.jsx
import { useState } from 'react';
import './App.css';

export default function App({ hello = '', serverTime = '', header, footer, children }) {
    const [count, setCount] = useState(0);

    return (
        <div className="island">
            <header className="island__header">
                {header ?? <h2>Hello, {hello}!</h2>}
            </header>

            <main className="island__main">
                <p>Rendered server-side at: <code>{serverTime}</code></p>
                <p>Hydrated client-side by React.</p>
                <button type="button" onClick={() => setCount(c => c + 1)}>
                    Clicked {count} times
                </button>
                {children}
            </main>

            <footer className="island__footer">
                {footer ?? <small>(no footer slot supplied)</small>}
            </footer>
        </div>
    );
}
